name: laundry_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  d_button: ^0.0.10
  d_info: ^0.2.0
  d_input: ^0.1.1
  d_method: ^0.2.1
  d_view: ^0.0.3
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
